// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/13/2026, 9:44:12 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/plugins/**/*.{js,ts,mjs}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/composables/**/*.{js,ts,mjs}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/utils/**/*.{js,ts,mjs}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/samue/Documents/Projects/TaxiPlus/taxiplus-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;